
import time

import ccxt
import pandas as pd
import pymysql
import telebot
import keys


telega_token = "5926919919:AAFCHFocMt_pdnlAgDo-13wLe4h_tHO0-GE"

one = ['NEOUSDT', 'LTCUSDT', 'QTUMUSDT', 'ADAUSDT', 'XRPUSDT', 'EOSUSDT', 'IOTAUSDT', 'XLMUSDT', 'ONTUSDT', 'TRXUSDT', 'ETCUSDT', 'ICXUSDT']

onedop = ['HMSTRUSDT', 'NULSUSDT', 'VETUSDT', 'LINKUSDT', 'ONGUSDT', 'HOTUSDT', 'ZILUSDT', 'ZRXUSDT', 'FETUSDT', 'BATUSDT', 'ZECUSDT', 'IOSTUSDT', 'CELRUSDT']

two = ['DASHUSDT', 'THETAUSDT', 'ENJUSDT', 'ATOMUSDT', 'TFUELUSDT', 'ONEUSDT', 'FTMUSDT', 'ALGOUSDT', 'DOGEUSDT', 'DUSKUSDT', 'ANKRUSDT']

twodop = ['WINUSDT', 'COSUSDT', 'MTLUSDT', 'DENTUSDT', 'KEYUSDT', 'WANUSDT', 'FUNUSDT', 'CVCUSDT', 'CHZUSDT', 'BANDUSDT', 'XTZUSDT', 'RENUSDT']

three = ['RVNUSDT', 'HBARUSDT', 'NKNUSDT', 'STXUSDT', 'KAVAUSDT', 'ARPAUSDT', 'IOTXUSDT', 'RLCUSDT', 'CTXCUSDT', 'BCHUSDT', 'TROYUSDT', 'VITEUSDT']

threedop = ['FTTUSDT', 'OGNUSDT', 'WRXUSDT', 'LSKUSDT', 'BNTUSDT', 'LTOUSDT', 'MBLUSDT', 'COTIUSDT', 'STPTUSDT', 'DATAUSDT', 'SOLUSDT', 'CTSIUSDT']

four = ['HIVEUSDT', 'CHRUSDT', 'ARDRUSDT', 'MDTUSDT', 'STMXUSDT', 'KNCUSDT', 'LRCUSDT', 'COMPUSDT', 'SCUSDT', 'ZENUSDT', 'SNXUSDT', 'VTHOUSDT']

fourdop = ['DGBUSDT', 'SXPUSDT', 'MKRUSDT', 'DCRUSDT', 'STORJUSDT', 'MANAUSDT', 'YFIUSDT', 'BALUSDT', 'BLZUSDT', 'IRISUSDT', 'KMDUSDT', 'JSTUSDT']

five = ['CATIUSDT', 'CRVUSDT', 'SANDUSDT', 'NMRUSDT', 'DOTUSDT', 'LUNAUSDT', 'RSRUSDT', 'TRBUSDT', 'SUSHIUSDT', 'KSMUSDT', 'EGLDUSDT', 'DIAUSDT', 'RUNEUSDT']

fivedop = ['FIOUSDT', 'UMAUSDT', 'BELUSDT', 'WINGUSDT', 'UNIUSDT', 'OXTUSDT', 'SUNUSDT', 'AVAXUSDT', 'FLMUSDT', 'ORNUSDT', 'UTKUSDT', 'XVSUSDT']

six = ['ALPHAUSDT', 'AAVEUSDT', 'NEARUSDT', 'FILUSDT', 'INJUSDT', 'AUDIOUSDT', 'CTKUSDT', 'AKROUSDT', 'AXSUSDT', 'HARDUSDT', 'STRAXUSDT', 'UNFIUSDT']

sixdop = ['EIGENUSDT', 'ROSEUSDT', 'AVAUSDT', 'SKLUSDT', 'GRTUSDT', 'JUVUSDT', 'PSGUSDT', '1INCHUSDT', 'OGUSDT', 'ATMUSDT', 'ASRUSDT', 'CELOUSDT']

seven = ['RIFUSDT', 'TRUUSDT', 'CKBUSDT', 'TWTUSDT', 'FIROUSDT', 'LITUSDT', 'SFPUSDT', 'DODOUSDT', 'CAKEUSDT', 'ACMUSDT', 'BADGERUSDT', 'FISUSDT']

sevendop = ['TURBOUSDT', 'SCRUSDT', 'OMUSDT', 'PONDUSDT', 'DEGOUSDT', 'ALICEUSDT', 'LINAUSDT', 'PERPUSDT', 'SUPERUSDT', 'CFXUSDT', 'TKOUSDT', 'PUNDIXUSDT', 'TLMUSDT', 'BARUSDT']

eight = ['BNSOLUSDT', 'FORTHUSDT', 'BAKEUSDT', 'BURGERUSDT', 'SLPUSDT', 'SHIBUSDT', 'ICPUSDT', 'ARUSDT', 'MASKUSDT', 'LPTUSDT', 'XVGUSDT', 'ATAUSDT', 'GTCUSDT']

eightdop = ['ERNUSDT', 'KLAYUSDT', 'PHAUSDT', 'MLNUSDT', 'DEXEUSDT', 'C98USDT', 'CLVUSDT', 'QNTUSDT', 'FLOWUSDT', 'MINAUSDT', 'RAYUSDT', 'FARMUSDT']

nine = ['ALPACAUSDT', 'QUICKUSDT', 'MBOXUSDT', 'REQUSDT', 'GHSTUSDT', 'WAXPUSDT', 'GNOUSDT', 'XECUSDT', 'ELFUSDT', 'DYDXUSDT', 'IDEXUSDT']

ninedop = ['VIDTUSDT', 'GALAUSDT', "CATIUSDT", 'ILVUSDT', 'YGGUSDT', 'SYSUSDT', 'DFUSDT', 'FIDAUSDT', 'AGLDUSDT', 'RADUSDT', 'BETAUSDT']

ten = ['RAREUSDT', 'LAZIOUSDT', 'CHESSUSDT', 'ADXUSDT', 'AUCTIONUSDT', 'DARUSDT', 'BNXUSDT', 'MOVRUSDT', 'CITYUSDT', 'ENSUSDT', 'KP3RUSDT', 'QIUSDT']

tendop = ['PORTOUSDT', 'POWRUSDT', 'JASMYUSDT', 'AMPUSDT', 'PYRUSDT', 'ALCXUSDT', 'SANTOSUSDT', 'BICOUSDT', 'FLUXUSDT', 'FXSUSDT', 'VOXELUSDT']

eleven = ['HIGHUSDT', 'CVXUSDT', 'PEOPLEUSDT', 'SPELLUSDT', 'JOEUSDT', "DOGSUSDT", 'ACHUSDT', 'IMXUSDT', 'GLMRUSDT', 'LOKAUSDT', 'SCRTUSDT', 'API3USDT']

elevendop = ['1MBABYDOGEUSDT', 'BTTCUSDT', 'ACAUSDT', 'XNOUSDT', 'WOOUSDT', 'ALPINEUSDT', 'TUSDT', 'ASTRUSDT', 'GMTUSDT', 'KDAUSDT', 'APEUSDT', 'BSWUSDT', 'BIFIUSDT', 'TONUSDT']

twelve = ['STEEMUSDT', 'NEXOUSDT', 'REIUSDT', 'LDOUSDT', 'OPUSDT', 'RENDERUSDT', 'LEVERUSDT', 'STGUSDT', 'LUNCUSDT', 'GMXUSDT', 'POLYXUSDT', 'APTUSDT', 'BANANAUSDT']

twelvedop = ['OSMOUSDT', 'HFTUSDT', 'PHBUSDT', 'HOOKUSDT', 'MAGICUSDT', 'HIFIUSDT', 'GUSDT', 'RPLUSDT', 'PROSUSDT', 'GNSUSDT', 'SYNUSDT', 'VIBUSDT', 'SSVUSDT', 'ZROUSDT']

thirteenth = ['LUMIAUSDT', 'LQTYUSDT', 'AMBUSDT', 'USTCUSDT', 'GASUSDT', 'BOMEUSDT', 'GLMUSDT', 'PROMUSDT', 'LISTAUSDT', 'QKCUSDT', 'UFTUSDT', 'IDUSDT', 'ARBUSDT', 'OAXUSDT', 'ZKUSDT']

thirteenthdop = ['RDNTUSDT', 'WBTCUSDT', 'EDUUSDT', 'SUIUSDT', 'AERGOUSDT', 'PEPEUSDT', 'IOUSDT', 'FLOKIUSDT', 'ASTUSDT', 'SNTUSDT', 'COMBOUSDT', 'MAVUSDT', 'PENDLEUSDT', 'NOTUSDT']

fourteenth = ['ARKMUSDT', 'WBETHUSDT', 'WLDUSDT', 'SEIUSDT', 'CYBERUSDT', 'ARKUSDT', 'BBUSDT', 'CREAMUSDT', "HMSTRUSDT", 'GFTUSDT', 'IQUSDT', 'NTRNUSDT', 'TIAUSDT', 'MEMEUSDT', 'REZUSDT']

fourteenthdop = ['ORDIUSDT', 'BEAMXUSDT', 'PIVXUSDT', 'VICUSDT', 'BLURUSDT', 'VANRYUSDT', 'OMNIUSDT', 'JTOUSDT', '1000SATSUSDT', 'BONKUSDT', 'ACEUSDT', 'NFPUSDT', 'AIUSDT', 'TAOUSDT']

fifteenth = ['XAIUSDT', 'MANTAUSDT', 'ALTUSDT', 'JUPUSDT', 'PYTHUSDT', 'RONINUSDT', 'SAGAUSDT', 'DYMUSDT', 'PIXELUSDT', 'STRKUSDT', 'PORTALUSDT', 'PDAUSDT', 'AXLUSDT', 'TNSRUSDT']

fifteenthdop = ['WIFUSDT', 'METISUSDT', 'AEVOUSDT', 'ETHFIUSDT', 'ENAUSDT', 'WUSDT', 'NEIROUSDT']

all_cripts_workss = one + two + three + four + five + six + seven + eight + nine + ten + eleven + twelve + thirteenth + fourteenth + fifteenth + \
    onedop + twodop + threedop + fourdop + fivedop + sixdop + sevendop + eightdop + ninedop + tendop + elevendop + twelvedop + \
    thirteenthdop + fourteenthdop + fifteenthdop

exchange = ccxt.binance()

def equal(crypto: str, all_profit: float, profit_deal: float, count_deal: float, average_deal_percent: float):
    try:
        values = (crypto, all_profit, profit_deal, count_deal, average_deal_percent)
        try:
            connection = pymysql.connect(host='127.0.0.1', port=3306, user='banan_user', password='warlight123',
                                             database='banans',
                                             cursorclass=pymysql.cursors.DictCursor)
            try:
                with connection.cursor() as cursor:
                    insert_query = ("INSERT INTO `check` "
                                    "(crypto, all_profit, profit_deal, count_deal, average_deal_percent) "
                                    "VALUES (%s, %s, %s, %s, %s)")
                    cursor.execute(insert_query, values)
                    connection.commit()
            finally:
                connection.close()

        except Exception as e:
            telebot.TeleBot(telega_token).send_message(-695765690, f"SQL ERROR equal connect k bd: {e}\n")

    except Exception as e:
        telebot.TeleBot(telega_token).send_message(-695765690, f"SQL ERROR equal: {e}\n")

x = []

for crypto in all_cripts_workss:
    symbol = f'{crypto[:-4]}/USDT'
    timeframe = '4h'
    limit = 2000

    try:
        ohlc = exchange.fetch_ohlcv(symbol, timeframe=timeframe, limit=limit)
    except Exception as e:
        print(f"Ошибка загрузки данных для {symbol}: {e}")
        continue

    df = pd.DataFrame(ohlc, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')

    # Рассчитываем процентное изменение закрытия за свечу
    df['change_percent'] = ((df['close'] - df['open']) / df['open']) * 100

    # Условие входа: цена упала больше чем на 5%
    df['buy_signal'] = df['change_percent'] <= -5

    position = False
    buy_price = 0
    profit = []

    for i in range(1, len(df)):
        if df['buy_signal'].iloc[i] and not position:
            buy_price = df['close'].iloc[i]
            position = True

        elif position:
            current_close_return = (df['close'].iloc[i] - buy_price) / buy_price * 100
            profit.append(current_close_return - 0.15)
            position = False

    total_profit = sum(profit)
    deal_count = len(profit)
    win_rate = len([x for x in profit if x > 0]) / deal_count * 100 if deal_count > 0 else 0
    avg_profit = total_profit / deal_count if deal_count > 0 else 0

    # === Отправка в БД по текущей монете ===
    equal(
        crypto=crypto,
        all_profit=float(f"{total_profit:.2f}"),
        profit_deal=float(f"{win_rate:.2f}"),
        count_deal=float(deal_count),
        average_deal_percent=float(f"{avg_profit:.2f}")
    )

    # === Вывод в консоль ===
    print(f"\n{crypto}")
    print(f"Общая прибыль: {total_profit:.2f}%")
    print(f"Процент прибыльных сделок: {win_rate:.2f}%")
    print(f"Всего сделок: {deal_count}")
    print(f"Средняя прибыль на сделку: {avg_profit:.2f}%")
    x.append([crypto, float(f"{total_profit:.2f}")])
    #equal(crypto, float(f"{total_profit:.2f}"), float(f"{win_rate:.2f}"))
    time.sleep(0.5)

print(x)

x = [['NEOUSDT', 38.7], ['LTCUSDT', 16.62], ['QTUMUSDT', 5.89], ['ADAUSDT', 50.52], ['XRPUSDT', 48.82], ['EOSUSDT', -10.62], ['IOTAUSDT', 53.35], ['XLMUSDT', 60.08], ['ONTUSDT', 37.78], ['TRXUSDT', 3.11], ['ETCUSDT', 2.25], ['ICXUSDT', 9.33], ['DASHUSDT', 23.69], ['THETAUSDT', 51.36], ['ENJUSDT', 41.45], ['ATOMUSDT', 16.65], ['TFUELUSDT', 17.04], ['ONEUSDT', 20.74], ['FTMUSDT', 31.89], ['ALGOUSDT', 71.45], ['DOGEUSDT', -6.19], ['DUSKUSDT', 35.92], ['ANKRUSDT', 33.6], ['RVNUSDT', 47.89], ['HBARUSDT', 88.72], ['NKNUSDT', 70.56], ['STXUSDT', 20.04], ['KAVAUSDT', 62.95], ['ARPAUSDT', 20.07], ['IOTXUSDT', 9.08], ['RLCUSDT', 41.15], ['CTXCUSDT', -33.35], ['BCHUSDT', 15.58], ['TROYUSDT', -81.63], ['VITEUSDT', -17.79], ['HIVEUSDT', 4.71], ['CHRUSDT', 19.05], ['ARDRUSDT', 37.62], ['MDTUSDT', 49.12], ['STMXUSDT', 113.84], ['KNCUSDT', 39.7], ['LRCUSDT', 51.36], ['COMPUSDT', 19.68], ['SCUSDT', 46.49], ['ZENUSDT', 29.24], ['SNXUSDT', 25.63], ['VTHOUSDT', 33.28], ['CATIUSDT', 54.37], ['CRVUSDT', 73.09], ['SANDUSDT', 61.57], ['NMRUSDT', 48.2], ['DOTUSDT', 10.48], ['LUNAUSDT', 4.12], ['RSRUSDT', 16.33], ['TRBUSDT', -49.19], ['SUSHIUSDT', -3.22], ['KSMUSDT', 3.94], ['EGLDUSDT', 41.4], ['DIAUSDT', 30.9], ['RUNEUSDT', 23.38], ['ALPHAUSDT', 52.57], ['AAVEUSDT', 3.15], ['NEARUSDT', 6.34], ['FILUSDT', 29.4], ['INJUSDT', 30.35], ['AUDIOUSDT', 59.76], ['CTKUSDT', -10.32], ['AKROUSDT', 7.39], ['AXSUSDT', 52.75], ['HARDUSDT', -0.1], ['STRAXUSDT', 76.59], ['UNFIUSDT', 47.8], ['RIFUSDT', 8.53], ['TRUUSDT', 34.59], ['CKBUSDT', 39.13], ['TWTUSDT', 49.54], ['FIROUSDT', -37.87], ['LITUSDT', -14.43], ['SFPUSDT', 31.98], ['DODOUSDT', 32.32], ['CAKEUSDT', 41.03], ['ACMUSDT', 10.47], ['BADGERUSDT', -7.14], ['FISUSDT', 10.84], ['BNSOLUSDT', 7.25], ['FORTHUSDT', -7.79], ['BAKEUSDT', 6.02], ['BURGERUSDT', -8.4], ['SLPUSDT', 38.04], ['SHIBUSDT', 49.07], ['ICPUSDT', 17.04], ['ARUSDT', 24.27], ['MASKUSDT', 45.61], ['LPTUSDT', 33.92], ['XVGUSDT', 29.55], ['ATAUSDT', 73.28], ['GTCUSDT', 25.87], ['ALPACAUSDT', 13.7], ['QUICKUSDT', 52.1], ['MBOXUSDT', 38.57], ['REQUSDT', 16.54], ['GHSTUSDT', -7.99], ['WAXPUSDT', 28.95], ['GNOUSDT', -6.26], ['XECUSDT', 39.4], ['ELFUSDT', 31.7], ['DYDXUSDT', 5.72], ['IDEXUSDT', 52.04], ['RAREUSDT', 44.06], ['LAZIOUSDT', -4.7], ['CHESSUSDT', 7.47], ['ADXUSDT', 17.0], ['AUCTIONUSDT', -17.02], ['DARUSDT', -14.57], ['BNXUSDT', 104.31], ['MOVRUSDT', -7.38], ['CITYUSDT', 10.4], ['ENSUSDT', -16.13], ['KP3RUSDT', -35.57], ['QIUSDT', 14.04], ['HIGHUSDT', 33.24], ['CVXUSDT', -43.13], ['PEOPLEUSDT', -3.61], ['SPELLUSDT', 7.91], ['JOEUSDT', 31.42], ['DOGSUSDT', -47.01], ['ACHUSDT', 46.85], ['IMXUSDT', 8.25], ['GLMRUSDT', 4.68], ['LOKAUSDT', 18.39], ['SCRTUSDT', -40.45], ['API3USDT', -1.17], ['STEEMUSDT', 29.06], ['NEXOUSDT', 60.38], ['REIUSDT', -12.43], ['LDOUSDT', -59.7], ['OPUSDT', 13.87], ['RENDERUSDT', 54.92], ['LEVERUSDT', 19.04], ['STGUSDT', 44.69], ['LUNCUSDT', 14.65], ['GMXUSDT', 65.58], ['POLYXUSDT', 45.57], ['APTUSDT', 16.24], ['BANANAUSDT', 69.9], ['LUMIAUSDT', 15.02], ['LQTYUSDT', 19.26], ['AMBUSDT', -90.33], ['USTCUSDT', 36.17], ['GASUSDT', 21.92], ['BOMEUSDT', -33.13], ['GLMUSDT', 23.99], ['PROMUSDT', 51.96], ['LISTAUSDT', 49.47], ['QKCUSDT', 35.78], ['UFTUSDT', -37.21], ['IDUSDT', 40.73], ['ARBUSDT', -14.24], ['OAXUSDT', -72.8], ['ZKUSDT', 34.13], ['ARKMUSDT', 47.64], ['WBETHUSDT', -29.06], ['WLDUSDT', 77.23], ['SEIUSDT', -16.47], ['CYBERUSDT', 33.35], ['ARKUSDT', 61.75], ['BBUSDT', 33.96], ['CREAMUSDT', -44.2], ['HMSTRUSDT', -40.53], ['GFTUSDT', -46.04], ['IQUSDT', 23.32], ['NTRNUSDT', -10.04], ['TIAUSDT', -19.02], ['MEMEUSDT', 33.74], ['REZUSDT', 121.06], ['XAIUSDT', -3.14], ['MANTAUSDT', 24.11], ['ALTUSDT', 7.89], ['JUPUSDT', -23.79], ['PYTHUSDT', -0.33], ['RONINUSDT', 17.51], ['SAGAUSDT', -7.54], ['DYMUSDT', -26.54], ['PIXELUSDT', 1.9], ['STRKUSDT', 15.81], ['PORTALUSDT', 45.2], ['PDAUSDT', 49.67], ['AXLUSDT', 44.63], ['TNSRUSDT', 8.11], ['HMSTRUSDT', -40.53], ['NULSUSDT', 50.22], ['VETUSDT', 10.9], ['LINKUSDT', 10.56], ['ONGUSDT', 46.01], ['HOTUSDT', 40.15], ['ZILUSDT', 45.2], ['ZRXUSDT', 55.16], ['FETUSDT', 36.47], ['BATUSDT', 54.83], ['ZECUSDT', 39.55], ['IOSTUSDT', 26.06], ['CELRUSDT', -1.25], ['WINUSDT', -5.14], ['COSUSDT', 27.94], ['MTLUSDT', 16.61], ['DENTUSDT', 43.84], ['KEYUSDT', 24.98], ['WANUSDT', 3.88], ['FUNUSDT', 1.71], ['CVCUSDT', 28.88], ['CHZUSDT', 41.64], ['BANDUSDT', -3.1], ['XTZUSDT', 47.8], ['RENUSDT', 17.4], ['FTTUSDT', 36.0], ['OGNUSDT', 8.44], ['WRXUSDT', 57.74], ['LSKUSDT', 26.07], ['BNTUSDT', 8.12], ['LTOUSDT', -16.72], ['MBLUSDT', 24.28], ['COTIUSDT', 38.75], ['STPTUSDT', 7.61], ['DATAUSDT', 13.19], ['SOLUSDT', 3.92], ['CTSIUSDT', 37.9], ['DGBUSDT', 29.11], ['SXPUSDT', 48.88], ['MKRUSDT', 8.64], ['DCRUSDT', 12.65], ['STORJUSDT', 22.51], ['MANAUSDT', 61.74], ['YFIUSDT', 33.68], ['BALUSDT', -13.7], ['BLZUSDT', 16.43], ['IRISUSDT', 7.82], ['KMDUSDT', 6.95], ['JSTUSDT', 2.6], ['FIOUSDT', -37.6], ['UMAUSDT', 38.1], ['BELUSDT', 49.45], ['WINGUSDT', -43.65], ['UNIUSDT', -26.7], ['OXTUSDT', 37.23], ['SUNUSDT', 34.94], ['AVAXUSDT', 11.37], ['FLMUSDT', -46.21], ['ORNUSDT', -18.59], ['UTKUSDT', 30.1], ['XVSUSDT', 58.2], ['EIGENUSDT', -14.21], ['ROSEUSDT', 36.54], ['AVAUSDT', 12.19], ['SKLUSDT', 50.94], ['GRTUSDT', 43.93], ['JUVUSDT', 9.06], ['PSGUSDT', 19.96], ['1INCHUSDT', 34.66], ['OGUSDT', -39.11], ['ATMUSDT', 16.83], ['ASRUSDT', -7.19], ['CELOUSDT', 36.62], ['TURBOUSDT', 17.23], ['SCRUSDT', 19.6], ['OMUSDT', 55.32], ['PONDUSDT', -8.25], ['DEGOUSDT', 132.86], ['ALICEUSDT', 7.96], ['LINAUSDT', -58.48], ['PERPUSDT', -29.36], ['SUPERUSDT', 46.61], ['CFXUSDT', 26.4], ['TKOUSDT', 26.55], ['PUNDIXUSDT', 59.2], ['TLMUSDT', 69.78], ['BARUSDT', 13.47], ['ERNUSDT', -9.73], ['KLAYUSDT', 12.72], ['PHAUSDT', 5.89], ['MLNUSDT', 5.21], ['DEXEUSDT', 23.57], ['C98USDT', 55.94], ['CLVUSDT', 72.17], ['QNTUSDT', 51.03], ['FLOWUSDT', 31.74], ['MINAUSDT', 47.91], ['RAYUSDT', 15.73], ['FARMUSDT', 22.24], ['VIDTUSDT', -5.81], ['GALAUSDT', 11.06], ['CATIUSDT', 54.37], ['ILVUSDT', 5.84], ['YGGUSDT', 18.83], ['SYSUSDT', 35.81], ['DFUSDT', -0.06], ['FIDAUSDT', 10.11], ['AGLDUSDT', 151.2], ['RADUSDT', -4.08], ['BETAUSDT', -155.14], ['PORTOUSDT', 2.82], ['POWRUSDT', 44.26], ['JASMYUSDT', 49.91], ['AMPUSDT', 12.62], ['PYRUSDT', 72.01], ['ALCXUSDT', 13.82], ['SANTOSUSDT', 31.2], ['BICOUSDT', 41.47], ['FLUXUSDT', 26.17], ['FXSUSDT', 25.26], ['VOXELUSDT', 54.73], ['1MBABYDOGEUSDT', 59.21], ['BTTCUSDT', 19.84], ['ACAUSDT', 4.0], ['XNOUSDT', -3.22], ['WOOUSDT', 17.0], ['ALPINEUSDT', 16.53], ['TUSDT', -0.06], ['ASTRUSDT', 50.24], ['GMTUSDT', 17.43], ['KDAUSDT', 35.91], ['APEUSDT', 26.27], ['BSWUSDT', -17.96], ['BIFIUSDT', -3.11], ['TONUSDT', 12.9], ['OSMOUSDT', 5.8], ['HFTUSDT', 68.15], ['PHBUSDT', 30.86], ['HOOKUSDT', 12.14], ['MAGICUSDT', 26.52], ['HIFIUSDT', -13.89], ['GUSDT', 90.31], ['RPLUSDT', 7.94], ['PROSUSDT', -62.19], ['GNSUSDT', 19.32], ['SYNUSDT', 75.94], ['VIBUSDT', -37.85], ['SSVUSDT', -25.98], ['ZROUSDT', 69.58], ['RDNTUSDT', 14.53], ['WBTCUSDT', 7.7], ['EDUUSDT', 4.22], ['SUIUSDT', 31.16], ['AERGOUSDT', 69.54], ['PEPEUSDT', 74.16], ['IOUSDT', 36.68], ['FLOKIUSDT', 46.28], ['ASTUSDT', 19.49], ['SNTUSDT', 56.43], ['COMBOUSDT', -64.16], ['MAVUSDT', 24.35], ['PENDLEUSDT', 7.52], ['NOTUSDT', 14.9], ['ORDIUSDT', 5.03], ['BEAMXUSDT', 27.04], ['PIVXUSDT', 6.69], ['VICUSDT', 4.68], ['BLURUSDT', 47.75], ['VANRYUSDT', -3.99], ['OMNIUSDT', -4.2], ['JTOUSDT', 35.36], ['1000SATSUSDT', 2.14], ['BONKUSDT', 80.25], ['ACEUSDT', 17.54], ['NFPUSDT', 25.46], ['AIUSDT', 35.66], ['TAOUSDT', 38.46], ['WIFUSDT', 23.78], ['METISUSDT', 2.34], ['AEVOUSDT', 28.68], ['ETHFIUSDT', 35.63], ['ENAUSDT', 56.02], ['WUSDT', 39.98], ['NEIROUSDT', 31.87]]

d = []

z6 = ['NEOUSDT', 'LTCUSDT', 'QTUMUSDT', 'ADAUSDT', 'XRPUSDT', 'EOSUSDT', 'IOTAUSDT', 'XLMUSDT', 'ONTUSDT', 'TRXUSDT', 'ETCUSDT', 'ICXUSDT', 'DASHUSDT', 'THETAUSDT', 'ENJUSDT', 'ATOMUSDT', 'TFUELUSDT', 'ONEUSDT', 'ALGOUSDT', 'DOGEUSDT', 'DUSKUSDT', 'ANKRUSDT', 'RVNUSDT', 'HBARUSDT', 'NKNUSDT', 'STXUSDT', 'KAVAUSDT', 'ARPAUSDT', 'IOTXUSDT', 'RLCUSDT', 'CTXCUSDT', 'BCHUSDT', 'TROYUSDT', 'HIVEUSDT', 'CHRUSDT', 'ARDRUSDT', 'MDTUSDT', 'STMXUSDT', 'KNCUSDT', 'LRCUSDT', 'COMPUSDT', 'SCUSDT', 'ZENUSDT', 'SNXUSDT', 'VTHOUSDT', 'CATIUSDT', 'CRVUSDT', 'SANDUSDT', 'DOTUSDT', 'LUNAUSDT', 'RSRUSDT', 'TRBUSDT', 'SUSHIUSDT', 'KSMUSDT', 'EGLDUSDT', 'DIAUSDT', 'RUNEUSDT', 'ALPHAUSDT', 'AAVEUSDT', 'NEARUSDT', 'FILUSDT', 'INJUSDT', 'AUDIOUSDT', 'CTKUSDT', 'AXSUSDT', 'HARDUSDT', 'STRAXUSDT', 'RIFUSDT', 'TRUUSDT', 'CKBUSDT', 'TWTUSDT', 'FIROUSDT', 'LITUSDT', 'SFPUSDT', 'CAKEUSDT', 'ACMUSDT', 'BADGERUSDT', 'FISUSDT', 'FORTHUSDT', 'BAKEUSDT', 'SLPUSDT', 'SHIBUSDT', 'ICPUSDT', 'ARUSDT', 'MASKUSDT', 'LPTUSDT', 'XVGUSDT', 'ATAUSDT', 'GTCUSDT', 'ALPACAUSDT', 'QUICKUSDT', 'MBOXUSDT', 'REQUSDT', 'GHSTUSDT', 'WAXPUSDT', 'GNOUSDT', 'XECUSDT', 'ELFUSDT', 'DYDXUSDT', 'IDEXUSDT', 'RAREUSDT', 'LAZIOUSDT', 'CHESSUSDT', 'ADXUSDT', 'AUCTIONUSDT', 'DARUSDT', 'BNXUSDT', 'MOVRUSDT', 'CITYUSDT', 'ENSUSDT', 'QIUSDT', 'HIGHUSDT', 'PEOPLEUSDT', 'SPELLUSDT', 'JOEUSDT', 'DOGSUSDT', 'ACHUSDT', 'IMXUSDT', 'GLMRUSDT', 'LOKAUSDT', 'SCRTUSDT', 'API3USDT', 'STEEMUSDT', 'NEXOUSDT', 'REIUSDT', 'LDOUSDT', 'RENDERUSDT', 'LEVERUSDT', 'STGUSDT', 'LUNCUSDT', 'GMXUSDT', 'POLYXUSDT', 'APTUSDT', 'BANANAUSDT', 'LUMIAUSDT', 'LQTYUSDT', 'USTCUSDT', 'GASUSDT', 'BOMEUSDT', 'GLMUSDT', 'PROMUSDT', 'LISTAUSDT', 'QKCUSDT', 'UFTUSDT', 'IDUSDT', 'ARBUSDT', 'ZKUSDT', 'ARKMUSDT', 'WBETHUSDT', 'WLDUSDT', 'SEIUSDT', 'CYBERUSDT', 'ARKUSDT', 'CREAMUSDT', 'HMSTRUSDT', 'IQUSDT', 'NTRNUSDT', 'TIAUSDT', 'MEMEUSDT', 'REZUSDT', 'XAIUSDT', 'MANTAUSDT', 'ALTUSDT', 'JUPUSDT', 'PYTHUSDT', 'RONINUSDT', 'SAGAUSDT', 'STRKUSDT', 'PORTALUSDT', 'PDAUSDT', 'AXLUSDT', 'TNSRUSDT', 'HMSTRUSDT', 'VETUSDT', 'LINKUSDT', 'ONGUSDT', 'HOTUSDT', 'ZILUSDT', 'ZRXUSDT', 'FETUSDT', 'BATUSDT', 'ZECUSDT', 'IOSTUSDT', 'CELRUSDT', 'WINUSDT', 'COSUSDT', 'MTLUSDT', 'DENTUSDT', 'WANUSDT', 'FUNUSDT', 'CVCUSDT', 'CHZUSDT', 'BANDUSDT', 'XTZUSDT', 'FTTUSDT', 'OGNUSDT', 'LSKUSDT', 'BNTUSDT', 'LTOUSDT', 'MBLUSDT', 'COTIUSDT', 'STPTUSDT', 'DATAUSDT', 'CTSIUSDT', 'DGBUSDT', 'SXPUSDT', 'MKRUSDT', 'DCRUSDT', 'STORJUSDT', 'MANAUSDT', 'YFIUSDT', 'BALUSDT', 'BLZUSDT', 'JSTUSDT', 'FIOUSDT', 'UMAUSDT', 'BELUSDT', 'UNIUSDT', 'OXTUSDT', 'SUNUSDT', 'AVAXUSDT', 'FLMUSDT', 'ORNUSDT', 'UTKUSDT', 'XVSUSDT', 'EIGENUSDT', 'ROSEUSDT', 'AVAUSDT', 'SKLUSDT', 'GRTUSDT', 'JUVUSDT', 'PSGUSDT', '1INCHUSDT', 'OGUSDT', 'ATMUSDT', 'ASRUSDT', 'CELOUSDT', 'TURBOUSDT', 'SCRUSDT', 'PONDUSDT', 'DEGOUSDT', 'ALICEUSDT', 'PERPUSDT', 'SUPERUSDT', 'CFXUSDT', 'TKOUSDT', 'PUNDIXUSDT', 'TLMUSDT', 'BARUSDT', 'ERNUSDT', 'PHAUSDT', 'MLNUSDT', 'DEXEUSDT', 'C98USDT', 'CLVUSDT', 'QNTUSDT', 'FLOWUSDT', 'MINAUSDT', 'RAYUSDT', 'FARMUSDT', 'VIDTUSDT', 'GALAUSDT', 'CATIUSDT', 'ILVUSDT', 'YGGUSDT', 'SYSUSDT', 'DFUSDT', 'FIDAUSDT', 'AGLDUSDT', 'RADUSDT', 'BETAUSDT', 'PORTOUSDT', 'POWRUSDT', 'JASMYUSDT', 'AMPUSDT', 'PYRUSDT', 'ALCXUSDT', 'SANTOSUSDT', 'BICOUSDT', 'FLUXUSDT', 'FXSUSDT', 'VOXELUSDT', '1MBABYDOGEUSDT', 'BTTCUSDT', 'ACAUSDT', 'XNOUSDT', 'WOOUSDT', 'ALPINEUSDT', 'TUSDT', 'ASTRUSDT', 'GMTUSDT', 'KDAUSDT', 'APEUSDT', 'BSWUSDT', 'BIFIUSDT', 'TONUSDT', 'OSMOUSDT', 'HFTUSDT', 'PHBUSDT', 'HOOKUSDT', 'MAGICUSDT', 'HIFIUSDT', 'GUSDT', 'RPLUSDT', 'PROSUSDT', 'GNSUSDT', 'SYNUSDT', 'VIBUSDT', 'SSVUSDT', 'ZROUSDT', 'RDNTUSDT', 'WBTCUSDT', 'EDUUSDT', 'SUIUSDT', 'AERGOUSDT', 'PEPEUSDT', 'IOUSDT', 'FLOKIUSDT', 'ASTUSDT', 'COMBOUSDT', 'MAVUSDT', 'PENDLEUSDT', 'NOTUSDT', 'BEAMXUSDT', 'PIVXUSDT', 'VICUSDT', 'BLURUSDT', 'VANRYUSDT', 'OMNIUSDT', 'JTOUSDT', 'BONKUSDT', 'ACEUSDT', 'NFPUSDT', 'AIUSDT', 'TAOUSDT', 'METISUSDT', 'AEVOUSDT', 'ETHFIUSDT', 'ENAUSDT', 'WUSDT', 'NEIROUSDT']

y = ['NEOUSDT', 'LTCUSDT', 'QTUMUSDT', 'ADAUSDT', 'XRPUSDT', 'EOSUSDT', 'IOTAUSDT', 'XLMUSDT', 'ONTUSDT', 'TRXUSDT', 'ETCUSDT', 'ICXUSDT', 'DASHUSDT', 'THETAUSDT', 'ENJUSDT', 'ATOMUSDT', 'TFUELUSDT', 'ONEUSDT', 'FTMUSDT', 'ALGOUSDT', 'DOGEUSDT', 'ANKRUSDT', 'RVNUSDT', 'HBARUSDT', 'NKNUSDT', 'STXUSDT', 'KAVAUSDT', 'ARPAUSDT', 'IOTXUSDT', 'RLCUSDT', 'BCHUSDT', 'TROYUSDT', 'HIVEUSDT', 'CHRUSDT', 'ARDRUSDT', 'MDTUSDT', 'STMXUSDT', 'KNCUSDT', 'LRCUSDT', 'COMPUSDT', 'SCUSDT', 'ZENUSDT', 'SNXUSDT', 'VTHOUSDT', 'CATIUSDT', 'CRVUSDT', 'SANDUSDT', 'DOTUSDT', 'LUNAUSDT', 'RSRUSDT', 'TRBUSDT', 'SUSHIUSDT', 'KSMUSDT', 'EGLDUSDT', 'DIAUSDT', 'RUNEUSDT', 'ALPHAUSDT', 'AAVEUSDT', 'NEARUSDT', 'FILUSDT', 'AUDIOUSDT', 'CTKUSDT', 'AKROUSDT', 'AXSUSDT', 'UNFIUSDT', 'RIFUSDT', 'TRUUSDT', 'CKBUSDT', 'TWTUSDT', 'FIROUSDT', 'LITUSDT', 'SFPUSDT', 'DODOUSDT', 'CAKEUSDT', 'ACMUSDT', 'BADGERUSDT', 'FISUSDT', 'BNSOLUSDT', 'FORTHUSDT', 'SLPUSDT', 'SHIBUSDT', 'ICPUSDT', 'ARUSDT', 'MASKUSDT', 'LPTUSDT', 'XVGUSDT', 'ATAUSDT', 'GTCUSDT', 'ALPACAUSDT', 'QUICKUSDT', 'REQUSDT', 'GHSTUSDT', 'WAXPUSDT', 'GNOUSDT', 'XECUSDT', 'ELFUSDT', 'DYDXUSDT', 'IDEXUSDT', 'RAREUSDT', 'LAZIOUSDT', 'ADXUSDT', 'AUCTIONUSDT', 'DARUSDT', 'BNXUSDT', 'MOVRUSDT', 'CITYUSDT', 'ENSUSDT', 'QIUSDT', 'SPELLUSDT', 'JOEUSDT', 'DOGSUSDT', 'ACHUSDT', 'IMXUSDT', 'GLMRUSDT', 'LOKAUSDT', 'SCRTUSDT', 'API3USDT', 'STEEMUSDT', 'NEXOUSDT', 'REIUSDT', 'OPUSDT', 'RENDERUSDT', 'LEVERUSDT', 'STGUSDT', 'LUNCUSDT', 'GMXUSDT', 'POLYXUSDT', 'APTUSDT', 'USTCUSDT', 'GASUSDT', 'GLMUSDT', 'PROMUSDT', 'LISTAUSDT', 'QKCUSDT', 'IDUSDT', 'ARBUSDT', 'ZKUSDT', 'ARKMUSDT', 'WBETHUSDT', 'WLDUSDT', 'SEIUSDT', 'CYBERUSDT', 'ARKUSDT', 'BBUSDT', 'CREAMUSDT', 'HMSTRUSDT', 'IQUSDT', 'NTRNUSDT', 'TIAUSDT', 'MEMEUSDT', 'REZUSDT', 'XAIUSDT', 'MANTAUSDT', 'ALTUSDT', 'JUPUSDT', 'PYTHUSDT', 'RONINUSDT', 'SAGAUSDT', 'DYMUSDT', 'PIXELUSDT', 'STRKUSDT', 'PDAUSDT', 'AXLUSDT', 'TNSRUSDT', 'HMSTRUSDT', 'NULSUSDT', 'VETUSDT', 'LINKUSDT', 'ONGUSDT', 'HOTUSDT', 'ZILUSDT', 'ZRXUSDT', 'FETUSDT', 'BATUSDT', 'ZECUSDT', 'IOSTUSDT', 'CELRUSDT', 'WINUSDT', 'COSUSDT', 'MTLUSDT', 'DENTUSDT', 'WANUSDT', 'FUNUSDT', 'CVCUSDT', 'CHZUSDT', 'BANDUSDT', 'XTZUSDT', 'RENUSDT', 'FTTUSDT', 'OGNUSDT', 'LSKUSDT', 'BNTUSDT', 'LTOUSDT', 'MBLUSDT', 'COTIUSDT', 'STPTUSDT', 'DATAUSDT', 'SOLUSDT', 'CTSIUSDT', 'DGBUSDT', 'SXPUSDT', 'MKRUSDT', 'DCRUSDT', 'STORJUSDT', 'MANAUSDT', 'YFIUSDT', 'BALUSDT', 'BLZUSDT', 'IRISUSDT', 'KMDUSDT', 'JSTUSDT', 'FIOUSDT', 'UMAUSDT', 'BELUSDT', 'UNIUSDT', 'OXTUSDT', 'SUNUSDT', 'AVAXUSDT', 'FLMUSDT', 'ORNUSDT', 'UTKUSDT', 'XVSUSDT', 'EIGENUSDT', 'ROSEUSDT', 'AVAUSDT', 'SKLUSDT', 'GRTUSDT', 'PSGUSDT', '1INCHUSDT', 'OGUSDT', 'ATMUSDT', 'ASRUSDT', 'CELOUSDT', 'TURBOUSDT', 'SCRUSDT', 'OMUSDT', 'PONDUSDT', 'DEGOUSDT', 'ALICEUSDT', 'PERPUSDT', 'SUPERUSDT', 'CFXUSDT', 'TKOUSDT', 'PUNDIXUSDT', 'TLMUSDT', 'BARUSDT', 'ERNUSDT', 'KLAYUSDT', 'PHAUSDT', 'MLNUSDT', 'DEXEUSDT', 'C98USDT', 'CLVUSDT', 'QNTUSDT', 'FLOWUSDT', 'MINAUSDT', 'RAYUSDT', 'FARMUSDT', 'GALAUSDT', 'CATIUSDT', 'ILVUSDT', 'YGGUSDT', 'SYSUSDT', 'DFUSDT', 'FIDAUSDT', 'AGLDUSDT', 'PORTOUSDT', 'POWRUSDT', 'JASMYUSDT', 'PYRUSDT', 'ALCXUSDT', 'SANTOSUSDT', 'BICOUSDT', 'FLUXUSDT', 'VOXELUSDT', '1MBABYDOGEUSDT', 'BTTCUSDT', 'ACAUSDT', 'XNOUSDT', 'WOOUSDT', 'ALPINEUSDT', 'TUSDT', 'ASTRUSDT', 'GMTUSDT', 'KDAUSDT', 'APEUSDT', 'BSWUSDT', 'BIFIUSDT', 'TONUSDT', 'OSMOUSDT', 'HFTUSDT', 'PHBUSDT', 'HOOKUSDT', 'MAGICUSDT', 'HIFIUSDT', 'GUSDT', 'RPLUSDT', 'PROSUSDT', 'GNSUSDT', 'ZROUSDT', 'RDNTUSDT', 'WBTCUSDT', 'EDUUSDT', 'SUIUSDT', 'AERGOUSDT', 'PEPEUSDT', 'IOUSDT', 'FLOKIUSDT', 'ASTUSDT', 'SNTUSDT', 'MAVUSDT', 'NOTUSDT', 'PIVXUSDT', 'VICUSDT', 'BLURUSDT', 'VANRYUSDT', 'OMNIUSDT', 'JTOUSDT', '1000SATSUSDT', 'BONKUSDT', 'ACEUSDT', 'AIUSDT', 'WIFUSDT', 'METISUSDT', 'AEVOUSDT', 'ETHFIUSDT', 'ENAUSDT', 'WUSDT']

z8 = ['NEOUSDT', 'LTCUSDT', 'QTUMUSDT', 'ADAUSDT', 'XRPUSDT', 'IOTAUSDT', 'XLMUSDT', 'ONTUSDT', 'TRXUSDT', 'ETCUSDT', 'ICXUSDT', 'DASHUSDT', 'THETAUSDT', 'ENJUSDT', 'ATOMUSDT', 'TFUELUSDT', 'ONEUSDT', 'FTMUSDT', 'ALGOUSDT', 'DOGEUSDT', 'DUSKUSDT', 'ANKRUSDT', 'RVNUSDT', 'HBARUSDT', 'NKNUSDT', 'STXUSDT', 'KAVAUSDT', 'ARPAUSDT', 'IOTXUSDT', 'RLCUSDT', 'BCHUSDT', 'HIVEUSDT', 'CHRUSDT', 'ARDRUSDT', 'MDTUSDT', 'STMXUSDT', 'KNCUSDT', 'LRCUSDT', 'COMPUSDT', 'SCUSDT', 'ZENUSDT', 'SNXUSDT', 'VTHOUSDT', 'CATIUSDT', 'CRVUSDT', 'SANDUSDT', 'NMRUSDT', 'DOTUSDT', 'LUNAUSDT', 'RSRUSDT', 'SUSHIUSDT', 'KSMUSDT', 'EGLDUSDT', 'DIAUSDT', 'RUNEUSDT', 'ALPHAUSDT', 'AAVEUSDT', 'NEARUSDT', 'FILUSDT', 'INJUSDT', 'AUDIOUSDT', 'AKROUSDT', 'AXSUSDT', 'HARDUSDT', 'STRAXUSDT', 'UNFIUSDT', 'RIFUSDT', 'TRUUSDT', 'CKBUSDT', 'TWTUSDT', 'SFPUSDT', 'DODOUSDT', 'CAKEUSDT', 'ACMUSDT', 'BADGERUSDT', 'FISUSDT', 'BNSOLUSDT', 'FORTHUSDT', 'BAKEUSDT', 'BURGERUSDT', 'SLPUSDT', 'SHIBUSDT', 'ICPUSDT', 'ARUSDT', 'MASKUSDT', 'LPTUSDT', 'XVGUSDT', 'ATAUSDT', 'GTCUSDT', 'ALPACAUSDT', 'QUICKUSDT', 'MBOXUSDT', 'REQUSDT', 'GHSTUSDT', 'WAXPUSDT', 'GNOUSDT', 'XECUSDT', 'ELFUSDT', 'DYDXUSDT', 'IDEXUSDT', 'RAREUSDT', 'LAZIOUSDT', 'CHESSUSDT', 'ADXUSDT', 'BNXUSDT', 'MOVRUSDT', 'CITYUSDT', 'QIUSDT', 'HIGHUSDT', 'PEOPLEUSDT', 'SPELLUSDT', 'JOEUSDT', 'ACHUSDT', 'IMXUSDT', 'GLMRUSDT', 'LOKAUSDT', 'API3USDT', 'STEEMUSDT', 'NEXOUSDT', 'OPUSDT', 'RENDERUSDT', 'LEVERUSDT', 'STGUSDT', 'LUNCUSDT', 'GMXUSDT', 'POLYXUSDT', 'APTUSDT', 'BANANAUSDT', 'LUMIAUSDT', 'LQTYUSDT', 'USTCUSDT', 'GASUSDT', 'GLMUSDT', 'PROMUSDT', 'LISTAUSDT', 'QKCUSDT', 'IDUSDT', 'ZKUSDT', 'ARKMUSDT', 'WLDUSDT', 'CYBERUSDT', 'ARKUSDT', 'BBUSDT', 'IQUSDT', 'MEMEUSDT', 'REZUSDT', 'XAIUSDT', 'MANTAUSDT', 'ALTUSDT', 'PYTHUSDT', 'RONINUSDT', 'SAGAUSDT', 'PIXELUSDT', 'STRKUSDT', 'PORTALUSDT', 'PDAUSDT', 'AXLUSDT', 'TNSRUSDT', 'NULSUSDT', 'VETUSDT', 'LINKUSDT', 'ONGUSDT', 'HOTUSDT', 'ZILUSDT', 'ZRXUSDT', 'FETUSDT', 'BATUSDT', 'ZECUSDT', 'IOSTUSDT', 'CELRUSDT', 'WINUSDT', 'COSUSDT', 'MTLUSDT', 'DENTUSDT', 'KEYUSDT', 'WANUSDT', 'FUNUSDT', 'CVCUSDT', 'CHZUSDT', 'BANDUSDT', 'XTZUSDT', 'RENUSDT', 'FTTUSDT', 'OGNUSDT', 'WRXUSDT', 'LSKUSDT', 'BNTUSDT', 'MBLUSDT', 'COTIUSDT', 'STPTUSDT', 'DATAUSDT', 'SOLUSDT', 'CTSIUSDT', 'DGBUSDT', 'SXPUSDT', 'MKRUSDT', 'DCRUSDT', 'STORJUSDT', 'MANAUSDT', 'YFIUSDT', 'BLZUSDT', 'IRISUSDT', 'KMDUSDT', 'JSTUSDT', 'UMAUSDT', 'BELUSDT', 'OXTUSDT', 'SUNUSDT', 'AVAXUSDT', 'UTKUSDT', 'XVSUSDT', 'ROSEUSDT', 'AVAUSDT', 'SKLUSDT', 'GRTUSDT', 'JUVUSDT', 'PSGUSDT', '1INCHUSDT', 'ATMUSDT', 'ASRUSDT', 'CELOUSDT', 'TURBOUSDT', 'SCRUSDT', 'OMUSDT', 'PONDUSDT', 'DEGOUSDT', 'ALICEUSDT', 'SUPERUSDT', 'CFXUSDT', 'TKOUSDT', 'PUNDIXUSDT', 'TLMUSDT', 'BARUSDT', 'ERNUSDT', 'KLAYUSDT', 'PHAUSDT', 'MLNUSDT', 'DEXEUSDT', 'C98USDT', 'CLVUSDT', 'QNTUSDT', 'FLOWUSDT', 'MINAUSDT', 'RAYUSDT', 'FARMUSDT', 'VIDTUSDT', 'GALAUSDT', 'CATIUSDT', 'ILVUSDT', 'YGGUSDT', 'SYSUSDT', 'DFUSDT', 'FIDAUSDT', 'AGLDUSDT', 'RADUSDT', 'PORTOUSDT', 'POWRUSDT', 'JASMYUSDT', 'AMPUSDT', 'PYRUSDT', 'ALCXUSDT', 'SANTOSUSDT', 'BICOUSDT', 'FLUXUSDT', 'FXSUSDT', 'VOXELUSDT', '1MBABYDOGEUSDT', 'BTTCUSDT', 'ACAUSDT', 'XNOUSDT', 'WOOUSDT', 'ALPINEUSDT', 'TUSDT', 'ASTRUSDT', 'GMTUSDT', 'KDAUSDT', 'APEUSDT', 'BIFIUSDT', 'TONUSDT', 'OSMOUSDT', 'HFTUSDT', 'PHBUSDT', 'HOOKUSDT', 'MAGICUSDT', 'GUSDT', 'RPLUSDT', 'GNSUSDT', 'SYNUSDT', 'ZROUSDT', 'RDNTUSDT', 'WBTCUSDT', 'EDUUSDT', 'SUIUSDT', 'AERGOUSDT', 'PEPEUSDT', 'IOUSDT', 'FLOKIUSDT', 'ASTUSDT', 'SNTUSDT', 'MAVUSDT', 'PENDLEUSDT', 'NOTUSDT', 'ORDIUSDT', 'BEAMXUSDT', 'PIVXUSDT', 'VICUSDT', 'BLURUSDT', 'VANRYUSDT', 'OMNIUSDT', 'JTOUSDT', '1000SATSUSDT', 'BONKUSDT', 'ACEUSDT', 'NFPUSDT', 'AIUSDT', 'TAOUSDT', 'WIFUSDT', 'METISUSDT', 'AEVOUSDT', 'ETHFIUSDT', 'ENAUSDT', 'WUSDT', 'NEIROUSDT']


# for i in x:
#     if i[1] > -10:
#         d.append(i[0])
#
# print(d)